version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=localhost
  #     - DB_USER=carlos
  #     - DB_PASSWORD=carlos
  #     - DB_NAME=teste
  #     - DB_PORT=5432
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=carlos
      - POSTGRES_DB=teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carlos -d teste"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: